languageCode = "en-us"
baseurl = "http://conf.tlapl.us/"
title = "TLA+ Community Event & Conference"
theme = "hugo-theme-learn"
pygmentsUseClassic = true
PygmentsCodeFences = true
publishDir = "docs"

[Params]
  Author = "Markus Kuppe"
  disableSearch = true
  disableInlineCopyToClipBoard = false
  disableAssetsBusting = true

## https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
[markup.goldmark.renderer]
  unsafe= true